version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "pub"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"