name: textformfield_datetime_range_picker
description: A customizable date and time range picker widget for Flutter applications.
version: 0.1.1
homepage: https://github.com/adampermana/textformfield_datetime_range_picker.git
repository: https://github.com/adampermana/textformfield_datetime_range_picker.git
issue_tracker: https://github.com/adampermana/textformfield_datetime_range_picker/issues
topics: [datetime-range-picker, datetime, textformfield, range-picker]

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <7.0.0"