name: textformfield_datetime_range_picker
description: A customizable date and time range picker widget for Flutter applications.
version: 0.0.3
homepage: https://github.com/adampermana/textformfield_datetime_range_picker.git
repository: https://github.com/adampermana/textformfield_datetime_range_picker.git
topics: [datetime-range-picker, datetime, textformfield, range-picker]
issue_tracker: https://github.com/adampermana/textformfield_datetime_range_picker/issues
license: MIT

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.1.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.19.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0