name: Publish

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Dart SDK (tanpa Flutter)
      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          sdk: stable

      # Install Flutter SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Validate pubspec.yaml
      - name: Validate pubspec.yaml
        run: flutter pub publish --dry-run

      # Publikasi ke pub.dev
      - name: Publish to pub.dev
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: |
          echo $PUB_DEV_TOKEN | dart pub publish --force --server=https://pub.dev
          bash scripts/credentials.sh
