name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Install Flutter SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: "stable"
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Validate pubspec.yaml
      - name: Validate pubspec.yaml
        run: flutter pub publish --dry-run

      # Publikasi ke pub.dev
      - name: Publish to pub.dev
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: |
          echo $PUB_DEV_TOKEN | flutter pub publish -f